;
; Project_1A.asm
;
; Created: 2/7/2019 6:29:52 PM
; Author : Cody Hudson
;

 .include<m328pdef.inc>

 start:
 .ORG 00
	; SETTING 'R22' FOR 8-BIT MULTIPLIER
	; FOR EXAMPLE MULTIPLIER IS '5'
	LDI R22, 0x05 ; 5
	LDI R23, 0x05 ; 5 SECOND VARIABLE NEEDED FOR MULTIPLIER
	; SETTING 'R25' AND 'R24' FOR 16-BIT MULTIPLICAND
	; FOR EXAMPLE 16-BIT IS '23373'
	LDI R25, 0x5B ; HIGH REGISTER
	LDI R24, 0x4D ; LOW REGISTER
	
	; FIRST LOOP PERFORMS ITERATIVE ADDITION EXITING AND
	; REJOINING WHENEVER THERE IS A CARRY TO LABEL 'C1' TO 
	; THE HIGH REGISTER
L1: ADD R19, R25 ; ITERATIVE ADDING OF 'MIDDLE NIBBLE'
	DEC R22 ; R22 = R22-1
	BRCS C1 ; IF CARRY SET GO TO 'C1'
	BRNE L1	; IF R22 DOES NOT EQUAL 0 BRANCH TO 'L1'

	; SECOND LOOP PERFORMS ITERATIVE ADDITION EXITING AND
	; REJOINING WHENEVER THERE IS A CARRY TO LABEL 'C2' TO 
	; THE LOW REGISTER
L2: ADD R18, R24 ; ITERATIVE ADDING OF 'RIGHT NIBBLE'
	DEC R23 ; R23 = R23-1
	BRCS C2 ; IF CARRY SET GO TO 'C2'
	BRNE L2	; IF R22 DOES NOT EQUAL 0 BRANCH TO 'L2'
END: 
	RJMP END ; CONTINUOUS LOOP TO END

	; COUNTS ALL THE CARRYS FROM 'MIDDLE NIBBLE' AND PLACES THEM IN
	; 'R20' FOR LEFT NIBBLE
C1: SUBI R20, -1 ; CREATING 'LEFT NIBBLE' 
	CLC	; CLEARS CARRY
	CPI R22,0 ; COMPARE 'R22' WITH INTEGER VALUE '0'
	BREQ L2 ; IF 'R22' = 0 BRANCH TO 'L2'
	RJMP L1 ; RETURN TO 'L1' IF ALL OTHER CONSTRAINTS HAVENT BEEN MET
	
	; COUNTS ALL THE CARRYS FROM THE 'RIGHT NIBBLE' AND ADDS THEM TO 
	; 'SECOND NIBBLE'
C2: SUBI R17, -1 ; CREATING CARRY FOR 'SECOND NIBBLE'
	CLC ; CLEARS CARRY
	ADD R19, R17 ; ADD CARRY FROM 'RIGHT NIBBLE' TO 'MIDDLE NIBBLE'
	BRCS C1 ; IF NOW THERE IS A NEW CARY GENERATED BRANCH TO 'C1'
	CPI R23, 0 ; COMPARE 'R23' WITH INTERGER VALUE '0'
	BREQ END ; IF 'R22' = 0 BRANCH TO 'END'
	RJMP L2; RETURN TO 'L2' IF ALL OTHER CONSTRAINTS HAVENT BEEN MET
